services:
  db:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10

  scraper:
    build: .
    depends_on:
      db:
        condition: service_healthy
