services:
  db:
    image: clickhouse/clickhouse-server
    env_file: .env
    # ports: ["8123:8123"]  # uncomment this to be able to connect to DB from outside
    volumes:
    - ./tables.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: wget --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10

  scraper:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
