services:
  api:
    build: .
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      DB_HOSTNAME: db
    ports:
    - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    env_file: .env
    environment:
      POSGRES_USER: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
